// Code generated by protoc-gen-go-micro. DO NOT EDIT.
// versions:
// - protoc-gen-go-micro v5.0.0-20260513173418-586c53efa787+dirty
// - protoc              v7.34.1
// source: health/health.proto

package health_handler

import (
	context "context"
	codec "go.unistack.org/micro-proto/v5/codec"
	client "go.unistack.org/micro/v5/client"
)

var (
	HealthServiceName = "HealthService"
)

type HealthServiceClient interface {
	Healthy(ctx context.Context, req *codec.Frame, opts ...client.CallOption) (*codec.Frame, error)
	Live(ctx context.Context, req *codec.Frame, opts ...client.CallOption) (*codec.Frame, error)
	Ready(ctx context.Context, req *codec.Frame, opts ...client.CallOption) (*codec.Frame, error)
	Version(ctx context.Context, req *codec.Frame, opts ...client.CallOption) (*codec.Frame, error)
}

type HealthServiceServer interface {
	Healthy(ctx context.Context, req *codec.Frame, rsp *codec.Frame) error
	Live(ctx context.Context, req *codec.Frame, rsp *codec.Frame) error
	Ready(ctx context.Context, req *codec.Frame, rsp *codec.Frame) error
	Version(ctx context.Context, req *codec.Frame, rsp *codec.Frame) error
}
