// Code generated by protoc-gen-go-micro. DO NOT EDIT.
// versions:
// - protoc-gen-go-micro v4.1.0
// - protoc              v5.29.3
// source: health/health.proto

package health_handler

import (
	context "context"
	codec "go.unistack.org/micro-proto/v4/codec"
	client "go.unistack.org/micro/v4/client"
)

var (
	HealthServiceName = "HealthService"
)

type HealthServiceClient interface {
	Healthy(ctx context.Context, req *codec.Frame, opts ...client.CallOption) (*codec.Frame, error)
	Live(ctx context.Context, req *codec.Frame, opts ...client.CallOption) (*codec.Frame, error)
	Ready(ctx context.Context, req *codec.Frame, opts ...client.CallOption) (*codec.Frame, error)
	Version(ctx context.Context, req *codec.Frame, opts ...client.CallOption) (*codec.Frame, error)
}

type HealthServiceServer interface {
	Healthy(ctx context.Context, req *codec.Frame, rsp *codec.Frame) error
	Live(ctx context.Context, req *codec.Frame, rsp *codec.Frame) error
	Ready(ctx context.Context, req *codec.Frame, rsp *codec.Frame) error
	Version(ctx context.Context, req *codec.Frame, rsp *codec.Frame) error
}
