// Code generated by protoc-gen-go-micro. DO NOT EDIT.
// versions:
// - protoc-gen-go-micro v4.10.2
// - protoc              v4.21.12
// source: health.proto

package health

import (
	context "context"
	codec "go.unistack.org/micro-proto/v4/codec"
	v4 "go.unistack.org/micro-server-http/v4"
)

var (
	HealthServiceName = "HealthService"
)
var (
	HealthServiceServerEndpoints = []v4.EndpointMetadata{
		{
			Name:   "HealthService.Live",
			Path:   "/live",
			Method: "GET",
			Body:   "",
			Stream: false,
		},
		{
			Name:   "HealthService.Ready",
			Path:   "/ready",
			Method: "GET",
			Body:   "",
			Stream: false,
		},
		{
			Name:   "HealthService.Version",
			Path:   "/version",
			Method: "GET",
			Body:   "",
			Stream: false,
		},
	}
)

type HealthServiceServer interface {
	Live(ctx context.Context, req *codec.Frame, rsp *codec.Frame) error
	Ready(ctx context.Context, req *codec.Frame, rsp *codec.Frame) error
	Version(ctx context.Context, req *codec.Frame, rsp *codec.Frame) error
}
