// Code generated by protoc-gen-go-micro. DO NOT EDIT.
// versions:
// - protoc-gen-go-micro v4.1.0
// - protoc              v5.29.3
// source: meter/meter.proto

package meter_handler

import (
	context "context"
	codec "go.unistack.org/micro-proto/v4/codec"
	client "go.unistack.org/micro/v4/client"
)

var (
	MeterServiceName = "MeterService"
)

type MeterServiceClient interface {
	Metrics(ctx context.Context, req *codec.Frame, opts ...client.CallOption) (*codec.Frame, error)
}

type MeterServiceServer interface {
	Metrics(ctx context.Context, req *codec.Frame, rsp *codec.Frame) error
}
