// Code generated by protoc-gen-go-micro. DO NOT EDIT.
// protoc-gen-go-micro version: v4.0.2
// source: meter/meter.proto

package meter

import (
	context "context"
	codec "go.unistack.org/micro-proto/v4/codec"
	v4 "go.unistack.org/micro-server-http/v4"
	options "go.unistack.org/micro/v4/options"
	server "go.unistack.org/micro/v4/server"
)

var (
	MeterServiceServerEndpoints = []v4.EndpointMetadata{
		{
			Name:   "MeterService.Metrics",
			Path:   "/metrics",
			Method: "GET",
			Body:   "",
			Stream: false,
		},
	}
)

type meterServiceServer struct {
	MeterServiceServer
}

func (h *meterServiceServer) Metrics(ctx context.Context, req *codec.Frame, rsp *codec.Frame) error {
	return h.MeterServiceServer.Metrics(ctx, req, rsp)
}

func RegisterMeterServiceServer(s server.Server, sh MeterServiceServer, opts ...options.Option) error {
	type meterService interface {
		Metrics(ctx context.Context, req *codec.Frame, rsp *codec.Frame) error
	}
	type MeterService struct {
		meterService
	}
	h := &meterServiceServer{sh}
	var nopts []options.Option
	nopts = append(nopts, v4.HandlerEndpoints(MeterServiceServerEndpoints))
	return s.Handle(&MeterService{h}, append(nopts, opts...)...)
}
