// Code generated by protoc-gen-go-micro. DO NOT EDIT.
// protoc-gen-go-micro version: v4.1.0
// source: meter/meter.proto

package meter_handler

import (
	context "context"
	v41 "go.unistack.org/micro-client-http/v4"
	codec "go.unistack.org/micro-proto/v4/codec"
	v4 "go.unistack.org/micro-server-http/v4"
	client "go.unistack.org/micro/v4/client"
	server "go.unistack.org/micro/v4/server"
	http "net/http"
)

var (
	MeterServiceServerEndpoints = []v4.EndpointMetadata{
		{
			Name:   "MeterService.Metrics",
			Path:   "/metrics",
			Method: "GET",
			Body:   "",
			Stream: false,
		},
	}
)

type meterServiceClient struct {
	c    client.Client
	name string
}

func NewMeterServiceClient(name string, c client.Client) MeterServiceClient {
	return &meterServiceClient{c: c, name: name}
}

func (c *meterServiceClient) Metrics(ctx context.Context, req *codec.Frame, opts ...client.CallOption) (*codec.Frame, error) {
	errmap := make(map[string]interface{}, 1)
	errmap["default"] = &codec.Frame{}
	opts = append(opts,
		v41.ErrorMap(errmap),
	)
	opts = append(opts,
		v41.Method(http.MethodGet),
		v41.Path("/metrics"),
	)
	rsp := &codec.Frame{}
	err := c.c.Call(ctx, c.c.NewRequest(c.name, "MeterService.Metrics", req), rsp, opts...)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

type meterServiceServer struct {
	MeterServiceServer
}

func (h *meterServiceServer) Metrics(ctx context.Context, req *codec.Frame, rsp *codec.Frame) error {
	return h.MeterServiceServer.Metrics(ctx, req, rsp)
}

func RegisterMeterServiceServer(s server.Server, sh MeterServiceServer, opts ...server.HandlerOption) error {
	type meterService interface {
		Metrics(ctx context.Context, req *codec.Frame, rsp *codec.Frame) error
	}
	type MeterService struct {
		meterService
	}
	h := &meterServiceServer{sh}
	opts = append(opts, v4.HandlerEndpoints(MeterServiceServerEndpoints))
	return s.Handle(s.NewHandler(&MeterService{h}, opts...))
}
