// Code generated by protoc-gen-go-micro. DO NOT EDIT.
// versions:
// - protoc-gen-go-micro v5.0.0-20260513173418-586c53efa787+dirty
// - protoc              v7.34.1
// source: meter/meter.proto

package meter_handler

import (
	context "context"
	codec "go.unistack.org/micro-proto/v5/codec"
	client "go.unistack.org/micro/v5/client"
)

var (
	MeterServiceName = "MeterService"
)

type MeterServiceClient interface {
	Metrics(ctx context.Context, req *codec.Frame, opts ...client.CallOption) (*codec.Frame, error)
}

type MeterServiceServer interface {
	Metrics(ctx context.Context, req *codec.Frame, rsp *codec.Frame) error
}
